"""initial budget mealplan schema

Revision ID: a4b2f8fd96f3
Revises:
Create Date: 2026-07-09 05:37:09.221252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4b2f8fd96f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_price_ref',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('pack_qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'region', 'unit', name='uq_price_name_region_unit')
    )
    op.create_index('ix_price_region_name', 'ingredient_price_ref', ['region', 'name'], unique=False)
    op.create_table('budget',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency in ('KRW','USD')", name='ck_budget_currency'),
    sa.CheckConstraint('amount > 0', name='ck_budget_amount_positive'),
    sa.CheckConstraint('period_end > period_start', name='ck_budget_period'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budget_household_period', 'budget', ['household_id', 'period_start'], unique=False)
    op.create_table('meal_plan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('household_id', sa.BigInteger(), nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mealplan_household_period', 'meal_plan', ['household_id', 'period_start'], unique=False)
    op.create_table('meal',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('recipe_name', sa.String(length=200), nullable=False),
    sa.Column('recipe_steps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_plan_date', 'meal', ['meal_plan_id', 'plan_date'], unique=False)
    op.create_table('meal_ingredient',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('meal_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('est_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingredient_meal', 'meal_ingredient', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredient_meal', table_name='meal_ingredient')
    op.drop_table('meal_ingredient')
    op.drop_index('ix_meal_plan_date', table_name='meal')
    op.drop_table('meal')
    op.drop_index('ix_mealplan_household_period', table_name='meal_plan')
    op.drop_table('meal_plan')
    op.drop_index('ix_budget_household_period', table_name='budget')
    op.drop_table('budget')
    op.drop_index('ix_price_region_name', table_name='ingredient_price_ref')
    op.drop_table('ingredient_price_ref')
    op.drop_table('household')
    # ### end Alembic commands ###
